version: '3'
services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf  # Mount the custom pg_hba.conf
    networks:
      - elastic-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - ELASTIC_PASSWORD=BqhgYopav*kT-ovIUSrX
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=BqhgYopav*kT-ovIUSrX
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-net
    volumes:
      - es_data:/usr/share/elasticsearch/data

  web:
    build: .
    container_name: flask-app
    command: >
      sh -c "until curl -u elastic:BqhgYopav*kT-ovIUSrX http://elasticsearch:9200; do echo waiting for elasticsearch; sleep 2; done;
             flask run --host=0.0.0.0 --port=5001"
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
      - ELASTICSEARCH_URL=http://elastic:BqhgYopav*kT-ovIUSrX@elasticsearch:9200
    depends_on:
      - elasticsearch
      - db
    networks:
      - elastic-net

networks:
  elastic-net:
    driver: bridge

volumes:
  postgres_data:
  es_data: